
# development:
#   adapter: postgresql
#   encoding: unicode
#   database: weeklybit
#   pool: 5
#   username: zachferland
#   password:
#   timeout: 5000
#   host: localhost

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: weeklybittest
#   pool: 5
#   username: zachferland
#   password:
#   timeout: 5000
#   host: localhost

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: weeklybittestproduction
#   pool: 5
#   username: zachferland
#   password:
#   timeout: 5000
#   host: localhost

  # --------------------------------

development:
  adapter: sqlite3
  encoding: unicode
  database: weeklybit
  pool: 5
  username: zachferland
  password:
  timeout: 5000
  host: localhost

test:
  adapter: sqlite3
  encoding: unicode
  database: weeklybittest
  pool: 5
  username: zachferland
  password:
  timeout: 5000
  host: localhost

production:
  adapter: sqlite3
  encoding: unicode
  database: weeklybittestproduction
  pool: 5
  username: zachferland
  password:
  timeout: 5000
  host: localhost